lib/sauce-connect-launcher.js

In a [previous fix](https://github.com/bermi/sauce-connect-launcher/pull/54) for handling an unhandled error, I used the `===` operator when I should have used the `!==` operator.  This is because I had lazily copy/pasted from an `else if` block that I believed was doing the same thing (but was actually checking that a string was _not_ present)
Shame on me. :disappointed: 
This PR:
1. Fixes the incorrect `===` operator to `!==` so that we're ensuring the index of the substring is NOT `-1` (which would indicate it does not exist)
2. Moves my condition up one position in the if/else block to group it with the similar condition above.
Tested this condition locally and verified that it correctly errors out now when `Sauce Connect could not establish a connection` is output in the sauce …

Fix incorrect equality operator

---

package.json

A newer version of Sauce Connect (build 1789) is available!

Update Sauce Connect to 4.3.12

---

package.json

On Debian and Ubuntu systems the node binary is named nodejs instead of node 8-(
This patch supports both ways to invoke node.
Today installing sauce-connect-launcher fails with:
> sauce-connect-launcher@0.13.0 postinstall /home/leutloff/node_modules/sauce-connect-launcher
> node scripts/install.js
sh: 1: node: not found
This changed is derived from fibers (https://github.com/laverdet/node-fibers/blob/master/package.json).

Support install with nodejs on standard Debian/Ubuntu-Systems, too.

---

lib/sauce-connect-launcher.js

Older version of tar, or lighter weight versions (e.g. the tar in BusyBox v1.23.2) do not support
using tar with the `xf` flags - making tar guess what file format the archive is.
We are already asserting that the file is of type of `.tar.gz` so we can safely assume this is a gzip
archive. Adding the `z` flag will support older versions of `tar` while still being fully compatible with
new versions.
Use case: attempting to use sauce-connect-launcher in an Alpine Linux Docker Container, with
BusyBox v1.23.2 - which does not support `tar xf`, giving the error `tar: invalid tar magic`

fix: support older versions of tar with `xzf` flag

---

lib/sauce-connect-launcher.js
package.json

This adds support for specifying an http proxy via `http_proxy` or `https_proxy` in the environment. If not specified, no proxy is used (ie. the current behavior).
This is handy for environments where routing internet traffic via a proxy is needed, and seems like it would solve #26.

Add http proxy support for download

---

README.md

`fastFailRexegps` should be `fastFailRegexps`.
cc @bermi

update readme typo in options

---

package.json

```sh
23 Sep 09:08:51 - ***********************************************************
23 Sep 09:08:51 - A newer version of Sauce Connect (build 2865) is available!
23 Sep 09:08:51 - Download it here:
23 Sep 09:08:51 - https://saucelabs.com/downloads/sc-4.4.0-osx.zip
23 Sep 09:08:51 - ***********************************************************
```

update saucelabs connect to 4.4.0

---

lib/sauce-connect-launcher.js
package.json

Replaces the hardcoded version with auto-resolving the latest version
from https://saucelabs.com/versions.json and also using the provided
checksums to verify the downloaded archive.
Fixes https://github.com/bermi/sauce-connect-launcher/issues/70

Auto-resolve latest versions and verify checksum

---

lib/sauce-connect-launcher.js

Prevents double ready callbacks when starting multiple tunnels

Unwatch readyfile when no longer needed

---

README.md
appveyor.yml
lib/process_options.js
lib/sauce-connect-launcher.js
lib/try_run.js
test/process_options.test.js
test/sauce-connect-launcher.test.js
test/try_run_test.js

Allow to retry tunnel creation multiple times with a configurable
timeout between retries.
@henryprecheur @jlipps any objections, feedback?
This has been requested by some ember folks and might also workaround the flakiness in the tests of this module.

Configurable connection retries

---

lib/sauce-connect-launcher.js

The api key is private and shouldn't be displayed.
Fixes https://github.com/bermi/sauce-connect-launcher/issues/91

Hide api key when printing sc arguments

---

README.md
lib/sauce-connect-launcher.js
test/sauce-connect-launcher.test.js

Instead of downloading the latest sc, allow to provide a custom
binary.
Fixes https://github.com/bermi/sauce-connect-launcher/issues/75

Allow to provide a custom executable

---

.travis.yml
lib/sauce-connect-launcher.js
package.json
test/sauce-connect-launcher.test.js

According to https://github.com/nodejs/LTS Node 0.10 has already reached
EOL and 0.12 will reach it soon.
Remove support for both versions.

Remove support for Node 0.x

---

README.md
lib/process_options.js
lib/sauce-connect-launcher.js
lib/try_run.js
test/fixture/spawn-sc.js
test/process_options.test.js
test/sauce-connect-launcher.test.js
test/try_run_test.js

Allow to run sc in detached mode and to specify a connectVersion when downloading and creating the tunnel.
There are various changes in the code to remove the global version and resolve a local version inside the function to allow running multiple versions in parallel and prevent misleading checksum errors once the latest version has been resolved.
Fixes version overriding using `SAUCE_CONNECT_VERSION`.
Replaces: https://github.com/bermi/sauce-connect-launcher/pull/104
Fixes: https://github.com/bermi/sauce-connect-launcher/issues/106

Detached mode and configurable version

---

.jshintrc
lib/sauce-connect-launcher.js
test/sauce-connect-launcher.test.js

The sc dir was previously only created when the version file was fetched,
which is not done when a custom version is provided.
Also change the tests to remove the sc file before each test to ensure
the bootstrapping always works.

Fix creating sc directory with a custom version set

---

lib/sauce-connect-launcher.js

This was an error I was hitting where sc was outputting:
ERROR: can't open pidfile /tmp/sc_client-<name >/1479705594315.pid

Catch 'ERROR:' messages from SC binary

---

lib/process_options.js
test/process_options.test.js

Add handling for single-letter uppercase-only SauceConnect flags
Currently cannot pass "-B" for example, since it will get converted
to "-b" that SauceConnect does not recognize.
@johanneswuerbach @bermi 
https://wiki.saucelabs.com/pages/viewpage.action?pageId=48365781

Add handling for single-letter uppercase-only SauceConnect flags

---

lib/sauce-connect-launcher.js

Allow custom `-x` option. 
Fixes https://github.com/bermi/sauce-connect-launcher/issues/143

Don't override custom -x

---

package-lock.json
package.json

This fixes bug report #151.
According to [1] the only "breaking" change in version 3.0.0 is the dropped support for older node versions (e.g. 4 and 5).
Node version 6 is still supported. Node version 7 is not tested but should still work.
Installed via:
> npm i https-proxy-agent@3
Also `npm i` and `npm audit fix` with the latest npm version was executed.
[1] https://github.com/TooTallNate/node-https-proxy-agent/releases/tag/3.0.0

Upgraded https-proxy-agent to version 3

---

package-lock.json
package.json

@johanneswuerbach Here we go... 🎉 
This pr tackles issue #155 
I don't know why the old package-lock was pointing to artifactory.skyscannertools.net instead of registry.npmjs.org so please let me know if this change would cause an issue.

update https-proxy-agent dependency to latest version
